(function(_ds){var window=this;/*

 Copyright 2015-present Dan Abramov
 SPDX-License-Identifier: MIT
*/
var V7=function(a,b,c){function d(){if(m)throw Error("You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.");return h}function e(r){if(typeof r!=="function")throw Error(`Expected the listener to be a function. Instead, received: '${typeof r}'`);if(m)throw Error("You may not call store.subscribe() while the reducer is executing. If you would like to be notified after the store has been updated, subscribe from a component and invoke store.getState() in the callback to access the latest state. See https://redux.js.org/api/store#subscribelistener for more details.");
let q=!0;l===k&&(l=k.slice());l.push(r);return function(){if(q){if(m)throw Error("You may not unsubscribe from a store listener while the reducer is executing. See https://redux.js.org/api/store#subscribelistener for more details.");q=!1;l===k&&(l=k.slice());l.splice(l.indexOf(r),1);k=null}}}function f(r){if(typeof r!=="object"||r===null)var q=!1;else{for(q=r;Object.getPrototypeOf(q)!==null;)q=Object.getPrototypeOf(q);q=Object.getPrototypeOf(r)===q}if(!q)throw Error(`Actions must be plain objects. Instead, the actual type was: '${typeof r}'. You may need to add middleware to your store setup to handle dispatching other values, such as 'redux-thunk' to handle dispatching functions. See https://redux.js.org/tutorials/fundamentals/part-4-store#middleware and https://redux.js.org/tutorials/fundamentals/part-6-async-logic#using-the-redux-thunk-middleware for examples.`);
if(typeof r.type==="undefined")throw Error('Actions may not have an undefined "type" property. You may have misspelled an action type string constant.');if(m)throw Error("Reducers may not dispatch actions.");try{m=!0,h=g(h,r)}finally{m=!1}q=k=l;for(let z=0;z<q.length;z++)(0,q[z])();return r}if(typeof b==="function"&&typeof c==="function"||typeof c==="function"&&typeof arguments[3]==="function")throw Error("It looks like you are passing several store enhancers to createStore(). This is not supported. Instead, compose them together to a single function. See https://redux.js.org/tutorials/fundamentals/part-4-store#creating-a-store-with-enhancers for an example.");
typeof b==="function"&&typeof c==="undefined"&&(c=b,b=void 0);if(typeof c!=="undefined"){if(typeof c!=="function")throw Error(`Expected the enhancer to be a function. Instead, received: '${typeof c}'`);return c(V7)(a,b)}if(typeof a!=="function")throw Error(`Expected the root reducer to be a function. Instead, received: '${typeof a}'`);let g=a,h=b,k=[],l=k,m=!1;f({type:zAa});const n={dispatch:f,subscribe:e,getState:d,replaceReducer:function(r){if(typeof r!=="function")throw Error(`Expected the nextReducer to be a function. Instead, received: '${typeof r}`);
g=r;f({type:AAa});return n},[W7]:function(){return{subscribe(r){function q(){r.next&&r.next(d())}if(typeof r!=="object"||r===null)throw new TypeError(`Expected the observer to be an object. Instead, received: '${typeof r}'`);q();return{unsubscribe:e(q)}},[W7](){return this}}}};return n},BAa=function(a=X7,b){switch(b.type){case "SCOPE":const c=new Map(a.Dh);c.set(b.scope,b.value);Y7(c);return Object.assign({},a,{Dh:c});case "CLEAR":return Y7(X7.Dh),X7;default:return a}},Y7=async function(a){const b=
await _ds.v(),c=new Map;try{const d=JSON.parse(await b.getStorage().get("devsite-selector","__global_store"));for(const e of d)c.set(e[0],e[1]);for(const [e,f]of a)c.set(e,f)}catch(d){}try{await b.getStorage().set("devsite-selector","__global_store",JSON.stringify([...c]))}catch(d){}};var zAa=`@@redux/INIT${Math.random().toString(36).substring(7).split("").join(".")}`,AAa=`@@redux/REPLACE${Math.random().toString(36).substring(7).split("").join(".")}`;var W7=typeof Symbol==="function"&&Symbol.observable||"@@observable";var X7={Dh:new Map},Z7=null,CAa=async function(a){try{const b=await (await _ds.v()).getStorage().get("devsite-selector","__global_store");if(b){const c=JSON.parse(b);if(c)for(const [d,e]of c)a.store.dispatch({type:"SCOPE",scope:d,value:e})}}catch(b){}},DAa=class{constructor(){this.store=V7(BAa);CAa(this)}dispatch(a){this.store.dispatch(a)}subscribe(a){return this.store.subscribe(a)}getState(){return this.store.getState()}};var EAa="track-type track-name track-metadata-eventdetail track-metadata-position track-metadata-region-tag track-metadata-snippet-file-url track-metadata-endgoal".split(" "),$7=function(a){a.o&&(_ds.D(a.eventHandler),a.eventHandler.listen(a.o,"click",b=>{FAa(a,b)}))},HAa=function(a){var b=[...a.children];for(var c of b)if(c.matches(".ds-selector-tabs")){if(b=c.getAttribute("data-ds-scope"))a.scope=b;const d=["ds-selector-tabs"];b=[...c.classList].filter(e=>!d.includes(e));a.classList.add(...b);c.classList.contains("devsite-no-overflow")&&
(a.noOverflow=!0);for(;c.childNodes.length;)a.appendChild(c.childNodes[0]);c.remove()}c=a.querySelectorAll(".kd-tabbed-horz");for(const d of c)d.matches(".kd-tabbed-horz")&&GAa(a,d)},JAa=async function(a){await window.customElements.whenDefined("devsite-tabs");await Promise.allSettled([...a.querySelectorAll(":scope > devsite-selector")].map(L=>L.ready()));var b=a.querySelector(":scope > devsite-tabs");b?await b.j:b=new _ds.XX;a.o=b;a.o.isTabList=!0;a.noOverflow&&(a.o.noOverflow=!0);a.firstElementChild&&
a.firstElementChild!==a.o?a.insertBefore(a.o,a.firstElementChild):a.contains(a.o)||a.appendChild(a.o);$7(a);b=a.querySelectorAll(":scope > section");for(var c of b){a.ma.push(c);var d=c.dataset.tab,e=void 0,f=!0,g=!0;let L=b="",O=a.ownerDocument.createElement("tab");if(d){var h=void 0;if(e=(h=a.o)==null?void 0:_ds.MX(h,d))O=e,f=!1,O.id&&(b=O.id)}d=a.ownerDocument.createElement("a");var k=O.querySelector("a");k&&(d=k,g=!1);e&&g&&(d.textContent=e.textContent,_ds.En(e));O.contains(d)||O.appendChild(d);
O.removeAttribute("aria-selected");k="";if(f){f=c.querySelector("h1,h2,h3,h4,h5,h6");var l=void 0;if(f&&((l=f.textContent)==null?void 0:l.trim())!==""){(f.classList.contains("two-line-tab")||f.querySelector(".two-line-tab"))&&O.classList.add("devsite-two-line");g="";f.id&&(L=f.id);k=f.querySelector(".firebase-platform-label");var m=void 0;if((m=k)==null?0:m.textContent)g=k.textContent.trim(),k.remove();var n=f.textContent||"";k=c.querySelector("[tab-label]");var r=void 0;if((r=k)==null?0:r.getAttribute("tab-label"))g=
`${k.getAttribute("tab-label")}`;if(f.hasAttributes())for(var q of EAa)k=f.getAttribute(q),k!==null&&_ds.NN(a,q,k,d);k=f.tagName;f.remove();if(g)f=a.ownerDocument.createElement("span"),f.dataset.tabLabel=g,f.textContent=n.trim(),d.appendChild(f),b||(b=_ds.Po(`${n} ${g}`));else if(d.append(...f.childNodes),!b){let Q;b=_ds.Po((Q=n)!=null?Q:"")||"tab"}}else n="Error",f&&(n=f.getAttribute("data-text")||"Error"),g&&(d.textContent=n),b||(b=_ds.Po(n))}else if(!b){let Q;b=_ds.Po((Q=O.textContent)!=null?Q:
"")||"tab"}_ds.zy(O,"controls",`tabpanel-${b}`);O.id||(O.id=b);d.id||(d.id=`aria-tab-${b}`);d.href||_ds.ig(d,`#${b}`);_ds.xy(d,"button");var z=void 0;e||(z=a.o)!=null&&_ds.NX(z,b)||(O.dataset.tab=b,L&&(O.id=L),_ds.jla(a.o,O));_ds.xy(c,"tabpanel");_ds.zy(c,"labelledby",`aria-tab-${b}`);a.insertTabHeadings&&k&&(e=document.createElement(k),e.classList.add("devsite-selector-tab-heading"),e.textContent=d.textContent,c.insertBefore(e,c.firstChild));c.dataset.tab=b;c.tabIndex=0;c.id=`tabpanel-${b}`}r=_ds.C().hash.substring(1);
q=_ds.C().searchParams.get("tab");(c=a.ma.find(L=>L.matches(".selected,.devsite-selected")))&&c.classList.remove("selected","devsite-selected");m=l=h=z=null;if(r){var G;z=(G=a.o)==null?void 0:_ds.NX(G,r)}if(!z&&q){let L;h=(L=a.o)==null?void 0:_ds.MX(L,_ds.Po(q))}if((G=a.store.getState().Dh.get(a.scope))&&a.scope!=="none"){if(!z&&!h&&G){let L;l=(L=a.o)==null?void 0:_ds.MX(L,G)}if(!z&&!h&&!l)for(const L of a.ma)if(L.querySelector(`devsite-selector[scope="${a.scope}"] [data-tab="${G}"]`)){m=L;break}}if(!(z||
h||l||m))for(const L of a.ma){let O;if((O=L.querySelector("devsite-selector"))==null?0:O.active){m=L;break}}z?a.active=`${z.dataset.tab}`:h?a.active=`${h.dataset.tab}`:l?a.active=`${l.dataset.tab}`:m?a.active=`${m.dataset.tab}`:c?a.active=`${c.dataset.tab}`:IAa(a);a.ea.resolve();a.rendered=!0},FAa=async function(a,b){if(!b.defaultPrevented&&(b.preventDefault(),b.stopPropagation(),a.ownerDocument.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs")),b.target)){b=b.target;for(var c;!c&&
b&&b!==a;){var d=void 0;((d=b)==null?void 0:d.tagName.toUpperCase())==="TAB"&&(c=b);let f;b=(f=b)==null?void 0:f.parentElement}var e;if((e=c)==null?0:e.dataset.tab)a.dispatchEvent(new CustomEvent("devsite-sticky-freeze",{bubbles:!0})),await _ds.Ih(),e=a.getBoundingClientRect(),a.active=c.dataset.tab,a.scope!=="none"&&a.store.dispatch({type:"SCOPE",scope:a.scope,value:a.active}),await _ds.Ko(),c=a.getBoundingClientRect(),d=_ds.zn(document),window.scrollTo({left:d.x,top:d.y+c.top-e.top}),_ds.Jh();a.o&&
(a=_ds.MX(a.o,a.active),a==null?0:a.id)&&(c=_ds.C(),c.searchParams.delete("tab"),c.hash=`${a.id}`,_ds.yo(c.href,!0))}},IAa=function(a){var b;let c;(b=a.o)==null?b=void 0:b=b.o?b.o[0]:void 0;if(b=(c=b)==null?void 0:c.dataset.tab)a.active=b},KAa=async function(a,b=""){if(a.o){var c=_ds.MX(a.o,a.active);if(c){_ds.UX(a.o,c);c=a8(a,b);var d=a8(a,a.active);if(d==null||!d.classList.contains("devsite-active")){if(d)c==null||c.classList.remove("devsite-active"),d==null||d.classList.add("devsite-active");else if(c&&
a.active!==b){a.active=b;return}a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}}}},a8=function(a,b){if(b)return a.ma.find(c=>c.matches(`[data-tab="${b}"]`))},GAa=function(a,b){var c=[...b.children];for(const d of c)if(d.matches("article")){c=a.ownerDocument.createElement("section");for(d.classList.contains("selected")&&c.classList.add("devsite-selected");d.childNodes.length;)c.appendChild(d.childNodes[0]);const e=c.querySelector("header");if(e){const f=a.ownerDocument.createElement("h3");
e.childNodes.length&&f.append(...e.childNodes);f.id=e.id;_ds.In(f,e)}a.appendChild(c);d.remove()}b.remove()},b8=class extends _ds.PN{Na(){return this}constructor(){super(["devsite-tabs"]);this.scope="auto";this.active="";this.insertTabHeadings=this.noOverflow=this.rendered=!1;this.ea=new _ds.Hh;this.ra=new _ds.Hh;Z7||(Z7=new DAa);this.store=Z7;this.oa=()=>{};this.eventHandler=new _ds.u;this.qa=!1;this.o=null;this.ma=[];_ds.MN(this,(0,_ds.Ag)`track-type`,(0,_ds.Ag)`track-name`,(0,_ds.Ag)`track-metadata-eventDetail`,
(0,_ds.Ag)`track-metadata-position`,(0,_ds.Ag)`track-metadata-region-tag`,(0,_ds.Ag)`track-metadata-snippet-file-url`,(0,_ds.Ag)`track-metadata-end-goal`)}async connectedCallback(){super.connectedCallback();this.qa?$7(this):(this.qa=!0,this.oa=this.store.subscribe(()=>{var a=this.store.getState();if(a.Dh.has(this.scope)&&this.scope!=="none"&&(a=a.Dh.get(this.scope))){let b;if((b=this.o)==null?0:_ds.MX(b,a))this.active=a}this.ra.resolve()}),HAa(this),await JAa(this));await this.ea.promise;await this.scrollToAnchor()}async ready(){return this.ea.promise}async scrollToAnchor(){const a=
_ds.C().hash;if(a){await this.j;const b=await _ds.v();let c;((c=this.o)==null?0:_ds.NX(c,a.substring(1)))&&await b.scrollToAnchor(a)}}disconnectedCallback(){super.disconnectedCallback();_ds.D(this.eventHandler);this.oa&&this.oa()}updated(a){super.updated(a);a.has("active")&&this.active&&KAa(this,a.get("active"))}};b8.prototype.disconnectedCallback=b8.prototype.disconnectedCallback;b8.prototype.connectedCallback=b8.prototype.connectedCallback;
_ds.w([_ds.I({type:String,La:!0}),_ds.x("design:type",Object)],b8.prototype,"scope",void 0);_ds.w([_ds.I({type:String,La:!0}),_ds.x("design:type",Object)],b8.prototype,"active",void 0);_ds.w([_ds.I({type:Boolean,La:!0}),_ds.x("design:type",Object)],b8.prototype,"rendered",void 0);_ds.w([_ds.I({type:Boolean,La:!0,Aa:"no-overflow"}),_ds.x("design:type",Object)],b8.prototype,"noOverflow",void 0);
_ds.w([_ds.I({type:Boolean,Aa:"data-insert-tab-headings"}),_ds.x("design:type",Object)],b8.prototype,"insertTabHeadings",void 0);try{customElements.define("devsite-selector",b8)}catch(a){console.warn("devsite.app.customElement.DevsiteSelector",a)};})(_ds_www);
