(function(_ds){var window=this;var M3=function(a,b){_ds.nq(a,"transform","translate3d("+b+"px,0px,0px)")};var P3=function(a){a.o=N3(a,".devsite-top-logo-row-wrapper-wrapper");a.j=N3(a,".devsite-collapsible-section");a.ea=N3(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.o}`);a.setAttribute("bottom-row--height",`${a.j}`);a.setAttribute("bottom-tabs--height",`${a.ea}`);a.style.setProperty("--devsite-js-top-row--height",`${a.o}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.j}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.ea}px`);O3(a);a.m.resolve()},
O3=function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.j&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.j-a.ea&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.va&&(_ds.nq(b,"transform",`translate3d(0, -${a.offset}px, 0)`),Q3(a),a.va=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.oa()}px`)},fua=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");
const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.D(a.ra);a.qa&&window.cancelAnimationFrame(a.qa);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.$g(b.offsetWidth,b.offsetHeight);b=new _ds.$g(c.offsetWidth,c.offsetHeight);var f=_ds.Dq(c),g=document.documentElement.getAttribute("dir")==="rtl"?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?
e:0,l=f?h:1;_ds.nq(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});M3(c,a.hasAttribute("search-active")?0:e);_ds.lq(a.ra,d,_ds.Zn,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),M3(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.qa=window.requestAnimationFrame(()=>{c.setAttribute("transition","");_ds.nq(d,"transform",
"scale3d("+l+",1,1)");M3(c,k)})}},gua=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=a==null?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Ko(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===
d&&e.focus(),c.setAttribute("disabled","")))}},hua=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.getBrowserEvent();_ds.Wn(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{document.body.removeAttribute("devsite-book-nav--open")});a.eventHandler.listen(window,"resize",()=>{R3(a)});a.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],()=>{R3(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||b.target.getAttribute("id")!=="devsite-hamburger-menu"||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},S3=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");
b.style.opacity="1";a.appendChild(b)}},Q3=function(a){a.j===0?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},R3=function(a){window.requestAnimationFrame(()=>{a.ya.Ra()})},N3=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},T3=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=
0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},U3=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Um(a,c,b))},iua=function(a,b){const c=a.querySelectorAll(".devsite-header-link");b=b.querySelectorAll(".devsite-header-link");const d=a.querySelector("devsite-language-selector");a=a.querySelector("devsite-user");for(const e of b)d?d.after(e):a&&a.before(e);c.forEach(e=>{e.remove()})},jua=class extends _ds.Vm{constructor(){super(...arguments);
this.eventHandler=new _ds.u;this.va=-1;this.ra=new _ds.u;this.qa=0;this.ua=new MutationObserver(()=>{P3(this)});this.ya=new _ds.Zh(()=>{P3(this);Q3(this)},15);this.authUser=void 0;this.offset=this.ea=this.j=this.o=0;this.updated=!1;this.m=new _ds.Hh}static get observedAttributes(){return["offset","search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;O3(this);break;case "search-active":fua(this);break;case "bottom-row--hidden":a=
c!==null,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),gua(this,a)}}connectedCallback(){hua(this);S3(this);Q3(this);P3(this);this.ua.observe(this,{childList:!0,subtree:!0});O3(this);const a=_ds.C();this.authUser=_ds.ko(_ds.lo(a.href),"authuser")}disconnectedCallback(){_ds.D(this.eventHandler);this.ua.disconnect()}oa(){return this.o+this.j-
this.offset}xa(){return this.o+this.j}ec(a){this.m&&this.m.resolve();this.m=new _ds.Hh;this.updated=!1;if(a){U3(this,a,".devsite-header-upper-tabs");U3(this,a,".devsite-collapsible-section");U3(this,a,".devsite-product-name-wrapper");U3(this,a,"devsite-language-selector");U3(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&T3(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(T3(c,b),c=_ds.C(),
c=_ds.ko(_ds.lo(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Um(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));iua(this,a)}!this.updated&&a&&(_ds.En(this),this.appendChild(a));S3(this);R3(this)}async ready(){return this.m.promise}};try{customElements.define("devsite-header",jua)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
