(function(_ds){var window=this;var Gpa=function(){return(0,_ds.R)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},Hpa=function(){return(0,_ds.R)('<div class="devsite-book-nav-blur"></div>')},Ipa=function(a){a=a.mB;a=_ds.oR(new _ds.Jy("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.OL(_ds.Vw(1)),XXX_2:_ds.OL(_ds.Vw(a))});return(0,_ds.R)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var Jpa="onpointerover"in window?"pointerover":"mouseover",N_=function(a){const b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Sm(a,"visually-hidden","",c))},Kpa=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;_ds.lq(a.eventHandler,a,_ds.Zn,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.ea.removeAttribute("animatable")});_ds.Sm(a,"animatable","");b=_ds.sg(a.ma`animatable`);b(a.background,"animatable","");b(a.ea,"animatable","");a.hasAttribute("collapsed")?(_ds.Sm(a,"aria-label","Hide side navigation",a.j),_ds.Sm(a,"data-title","Hide side navigation",a.j),a.removeAttribute("collapsed"),_ds.zy(a.j,"expanded","true"),O_(a,"Expanded book nav")):(_ds.Sm(a,"aria-label","Show side navigation",
a.j),_ds.Sm(a,"data-title","Show side navigation",a.j),_ds.Sm(a,"collapsed",""),_ds.zy(a.j,"expanded","false"),O_(a,"Collapsed book nav"),_ds.lq(a.eventHandler,a,_ds.Zn,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.Ko();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},Mpa=function(a){a.eventHandler.listen(a,"click",b=>void P_(a,b));a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&P_(a,b)});a.eventHandler.listen(a,
[Jpa,"focusin"],b=>void Lpa(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.o&&(Q_(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Sm(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.xa.Ra());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.xa.Ra()});a.eventHandler.listen(a,"scroll",()=>{_ds.Sm(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",()=>{a.Ea.Ra()});a.m&&(a.eventHandler.listen(a.m,"keyup",()=>void a.ya.Ra()),
a.eventHandler.listen(a.m,"focus",()=>void R_(a,"focus")));a.qa&&a.eventHandler.listen(a.qa,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.m&&(a.m.value="",a.m.focus());let c;(c=a.qa)==null||c.classList.add("hidden");S_(a);T_(a);R_(a,b.type)}})},U_=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.oa=new Set(b);if(!_ds.C().hash&&c)Npa(a,a.oa);else{c=new _ds.IU;for(const d of a.oa)_ds.HU(c,d)}},V_=async function(a){const b=await _ds.v();
for(const c of a.oa)b.unregisterIntersectionForElement(c)},P_=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Sm(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&Q_(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=
c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.Sm(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||
(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},Lpa=function(a,b){b.defaultPrevented||(b=_ds.Vn(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.ig(b,_ds.Do(b.href).href))},R_=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:b,label:b==="focus"?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},W_=function(a){a.ra=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},Y_=function(a){const b=_ds.C().searchParams.get("nf");a.m&&b&&(a.m.value=b,X_(a))},X_=function(a){if(a.ra.length){S_(a);T_(a);var b,c,d=(b=a.m)==null?void 0:(c=b.value)==null?void 0:
c.trim().toLowerCase();if(d){var e;(e=a.qa)==null||e.classList.remove("hidden");for(const g of a.ra){var f=g.querySelectorAll(".devsite-nav-text");a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l;const m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(q=>q.toLowerCase().includes(d));let n,r;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(r=n.textContent)==null?0:r.toLowerCase().includes(d))))e=c=!0;else for(const q of f){let z,
G,L,O;f=((O=(z=q)==null?void 0:(G=z.parentElement)==null?void 0:(L=G.getAttribute("data-synonyms"))==null?void 0:L.split(","))!=null?O:[]).some(Q=>Q.toLowerCase().includes(d));if(d){let Q;if(f||((Q=q.textContent)==null?0:Q.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const q of c){q.classList.remove("hidden");let z,G,L,O;c=((O=(z=q)==null?void 0:(G=z.parentElement)==null?void 0:(L=G.getAttribute("data-synonyms"))==
null?void 0:L.split(","))!=null?O:[]).some(M=>M.toLowerCase().includes(d));let Q;d&&(c||((Q=q.textContent)==null?0:Q.toLowerCase().includes(d)))&&++b}}Opa(g,d)}a&&b>0&&Ppa(g,b)}}else(f=a.qa)==null||f.classList.add("hidden")}},S_=function(a){for(const b of a.ra){let c;b.classList.toggle("hidden",!((c=a.m)==null||!c.value))}},T_=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];
for(const c of a){a=c.parentElement;let d;b=(d=a)==null?void 0:d.textContent;a&&b&&_ds.qg(a,_ds.Tg(b))}}},Opa=function(a,b){if(a=a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.qg(a,_ds.Tg(d))}},Ppa=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.qu(Ipa,{mB:b}),a.appendChild(b)},Npa=async function(a,b){if(a.connected){var c=await _ds.v(),d=new _ds.IU,e=f=>{f=f.target;_ds.HU(d,f);a.oa.delete(f);
c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},Q_=function(a,b){let c=!1;if(a.o)for(const d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.Sm(a,"hidden","",d);return c},Z_=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-current");a=_ds.Ro(_ds.C().pathname);a=`[href="${_ds.Do(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.zy(c,"current","page")},$_=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},Qpa=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Ko(),await a0(a),await a.Ca,
await _ds.v(),await _ds.Ko(),await a0(a))},a0=async function(a){if(a.connected&&a.o){await _ds.v();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await Rpa(a,b))}},Rpa=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.wq(b,a,!0).y;await _ds.Ko();c&&_ds.Sm(a,"user-scrolled","")}},O_=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},
bubbles:!0}))},b0=class extends _ds.Vm{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.qa=this.m=this.ua=this.o=null;this.ra=[];this.eventHandler=new _ds.u;this.va=()=>{};this.oa=new Set;_ds.Rm(this,this.ma`animatable`,this.ma`aria-expanded`,this.ma`aria-label`,this.ma`collapsed`,this.ma`data-title`,this.ma`fixed`,this.ma`has-book-nav`,this.ma`hidden`,this.ma`top-level-nav`,this.ma`user-scrolled`,this.ma`visually-hidden`);this.background=
document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.j=_ds.qu(Gpa);this.ea=_ds.qu(Hpa);this.Ca=new Promise(a=>{this.va=a});this.xa=new _ds.Zh(()=>{this.connected&&N_(this)},20);this.ya=new _ds.Zh(()=>{X_(this)},20);this.Ea=new _ds.Zh(()=>{Kpa(this)},100)}async connectedCallback(){this.connected=!0;_ds.Fn(this.background,this);this.hasAttribute("hidden")&&(_ds.Sm(this,"hidden","",this.j),_ds.Sm(this,"hidden","",this.ea));let a;(a=this.parentElement)==null||a.insertBefore(this.j,
this.nextSibling);_ds.Sm(this,"aria-label","Hide side navigation",this.j);_ds.Sm(this,"data-title","Hide side navigation",this.j);_ds.Sm(this,"aria-expanded","true",this.j);let b;(b=this.parentElement)==null||b.insertBefore(this.ea,this.nextSibling);if(this.ua=this.querySelector(".devsite-book-nav-filter"))this.m=this.ua.querySelector("input[type=text]"),this.qa=this.ua.querySelector(".filter-clear-button"),W_(this),Y_(this);N_(this);Mpa(this);await this.init();U_(this)}disconnectedCallback(){this.connected=
!1;_ds.D(this.eventHandler);V_(this);this.oa.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.Sm(this,"visually-hidden","",a);a=[this.background,this.j,this.ea];for(const b of a)b&&_ds.Hn(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.ea.removeAttribute("animatable");this.ea.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?
"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Sm(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);const c=[this.background,this.j,this.ea];for(const d of c)d&&(b?_ds.Sm(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.va()}async init(a=!0){if(this.connected){this.ea.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");_ds.Sm(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.Sm(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.Sm(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(Z_(this),$_(this),await Qpa(this)):(await _ds.Ko(),await a0(this))}}async ec(a){a?
(a=a.querySelector("nav")||null,Z_(this,a),$_(this,a),a&&(await V_(this),this.oa.clear(),U_(this,a,!1)),_ds.Um(this,this.querySelector("nav"),a)):_ds.En(this);W_(this);if(this.m){this.m.value="";let b;(b=this.qa)==null||b.classList.add("hidden");Y_(this)}await _ds.Ko();await this.init(!1)}};b0.prototype.updateContent=b0.prototype.ec;b0.prototype.attributeChangedCallback=b0.prototype.attributeChangedCallback;b0.prototype.disconnectedCallback=b0.prototype.disconnectedCallback;
b0.prototype.connectedCallback=b0.prototype.connectedCallback;try{customElements.define("devsite-book-nav",b0)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
